### ISSUE TITLE
Code 39 issues

### ISSUE THREAD

**Issue by spazzymoto** [PDF417/pdf417-phonegap#10]
Hey guys,
Been testing out your plugin on PDF417 and Code 39 barcodes, the PDF417 works great but im struggling with the code 39.

On android once its finished scanning the app crashes, if i remove the line referencing the data ie something.innerHtml = data.data then it scans and closes the scanner and doesnt crash. 

On ios it scans but doesnt return what i was expecting, ie barcode = 7401015040088 and app returned something like *7*.

If i scan the barcode from the app in the play store it works beautifully.

Any ideas? i can email you a copy of the barcode i am trying to scan if that will help.

**Comment by ssasa** [comment]
Few months later this is updated. Hopefully better now than never.
