### ISSUE TITLE
Demo app shows "Class not found" when trying to scan

### ISSUE THREAD

**Issue by pierredup** [PDF417/pdf417-phonegap#13]
When using the demo app, or using the plugin in a custom app and trying to run it, shows the following error: "Class not found"

**Comment by Cerovec** [comment]
Hi Pierre,
do you experience this on iOS, Android or both versions of the plugin?

**Comment by pierredup** [comment]
Only on Android, I have not tested on iOS yet

**Comment by pierredup** [comment]
After some more testing, I found that this error only happens when using phonegap connect.
When packaging the app into an apk and installing on a device I don't get the error, but I do get "invlaid license key" when I don't use a license key

**Comment by ssasa** [comment]
License key is valid only for the demo app. Try removing the license key and then the SDK will work in demo mode (but it will work).

**Comment by Cerovec** [comment]
Hi Pierre,
do you still experience the issues?
