### ISSUE TITLE
Custom Overlay

### ISSUE THREAD

**Issue by collinforrester** [PDF417/pdf417-phonegap#14]
Is it possible or on the road map to provide this feature on iOS?  It'd be nice if we could provide our own overlay with some instructions.

**Comment by Cerovec** [comment]
Hi Colin,

you can use custom overlays in our native [iOS](https://github.com/pdf417/pdf417-ios/) and [Android](https://github.com/pdf417/pdf417-android/) pdf417 SDKs. Phonegap plugin doesn't support this feature.

To use custom overlays in phonegap, you can use native SDK, implement custom overlay there, and then wrap the whole component in a phonegap plugin. You can use the plugin code available in this repository as a reference.

**Comment by collinforrester** [comment]
Thanks!  We'll look into using the native SDK.
