### ISSUE TITLE
Unable to scan with mode USDL

### ISSUE THREAD

**Issue by collinforrester** [PDF417/pdf417-phonegap#15]
The title isn't entirely true, I can scan USDL with the demo app but when I try it with my code the barcode never gets recognized.  Mode PDF417 and QR code still work after upgrading to the most recent but USDL doesn't.. Any ideas why it wouldn't work?  We're having a tough time handling the different formats and we'd love to be able to use the hard work you guys have already put into parsing USDL.

The code is copy pasted from the demo app with the exception that I set types array to ONLY `['USDL']`.. that wouldn't matter, would it?

**Comment by ssasa** [comment]
Please contact us at our support help.microblink.com together with the package name / bundle ID and we will generate a demo license key which should make USDL API work.
