### ISSUE TITLE
iPad Air 2 QR scanning issues

### ISSUE THREAD

**Issue by collinforrester** [PDF417/pdf417-phonegap#16]
Has anyone else reported issues scanning a QR code with this library on the new iPad Air 2?

**Comment by Cerovec** [comment]
Actually, no. We can confirm that pdf417-phonegap works on iPad Air 2, even on iOS 9.
This might be an issue with the QR code - either it's too small, or you use front facing camera. Or the QR code is held too far from the camera... 

Can you give more details please? A photo of the QR code would be ideal.

**Comment by dannyniceboy** [comment]
I am unable to scan QR codes using the front camera on the iPad air 2.  It works on other ipads with the front camera with no issues.

![screen shot 2015-08-19 at 7 38 55 pm](https://cloud.githubusercontent.com/assets/633463/9372939/1ccd6f10-46aa-11e5-98f7-3c330118098b.png)

**Comment by Cerovec** [comment]
We successfully used pdf417-phonegap iOS plugin on iPad Air 2 to scan that QR code with front facing camera.

Try printing the QR code and using the paper above the device placed on the table.

If you try to scan from screen, you have to hold the device very close to the screen, and it's hard to position the device appropriately.

Also, implementation-wise, make sure "QR code" is included in the types array, and that frontFace camera is selected.

```javascript
var types = ["PDF417", "QR Code"];

        /**
         * Initiate scan with options
         * NOTE: Some features are unavailable without a license
         * Obtain your key at http://pdf417.mobi
         */
        var options = {
            beep : true,  // Beep on
            noDialog : true, // Skip confirm dialog after scan
            uncertain : false, //Recommended
            quietZone : false, //Recommended
            highRes : false, //Recommended
            inverseScanning: false,
            frontFace : true
        };
```

**Comment by Cerovec** [comment]
Attached scanning result.
![img_0010](https://cloud.githubusercontent.com/assets/628039/9378884/4c24b2e8-4725-11e5-9c1c-756081c8d2d6.png)

**Comment by collinforrester** [comment]
Thanks for the debugging help @Cerovec .   Would it matter if I am on an older version of the plugin?  In the `plugin.xml` it looks like version 1.0.3.

I'm not sure about @dannyniceboy

**Comment by Cerovec** [comment]
We definitely recommend using the current release [v1.0.2](https://github.com/PDF417/pdf417-phonegap/releases/tag/v1.0.2)

It looks like version in plugin.xml isn't synchronised with Github version - sorry about that. But I can confirm that the last release should be backwards compatible.

**Comment by collinforrester** [comment]
Are we able to upgrade to this version without purchasing it again or how does this work?  Are you saying to just upgrade the PG code and it should be fine?

**Comment by Cerovec** [comment]
You can just upgrade the PG plugin.

Depending on the version you currently have, the license key format is
probably changed. You can check this by upgrading the plugin, and testing
if the scanner works as before. If you see the license error, please
contact our support at support@microblink.com to get new iOS and Android
license keys (we do not charge for this license key upgrade).

Kind regards,
Jurica.

On Thu, Aug 20, 2015 at 3:44 PM, Collin Forrester <notifications@github.com>
wrote:

> Are we able to upgrade to this version without purchasing it again or how
> does this work? Are you saying to just upgrade the PG code and it should be
> fine?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDF417/pdf417-phonegap/issues/16#issuecomment-133011993>
> .
>



-- 
Jurica Cerovec, M.Sc.

mobile: +385 98 993 8076
skype: cerovec

http://photomath.net
http://microblink.com

**Comment by collinforrester** [comment]
Awesome, thank you!
