### ISSUE TITLE
windows phone version build issue.

### ISSUE THREAD

**Issue by sirius2013** [PDF417/pdf417-phonegap#17]
![image](https://cloud.githubusercontent.com/assets/5020713/10715568/bad3837c-7b55-11e5-84a6-3ea8834821d1.png)

**Comment by sirius2013** [comment]
Hi Team,
I followed your direction, and when I tried to build with Visual Studio 2013. I got error, I sent screenshot on the previous comment,

Error	1	There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture, "ARM", of the implementation file "C:\Work\KnowledgeCenter\PatientTracker\platforms\wp8\plugins\mobi.pdf417.Pdf417Scanner\Microblink.dll" for "C:\Work\KnowledgeCenter\PatientTracker\platforms\wp8\plugins\mobi.pdf417.Pdf417Scanner\Microblink.winmd". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and implementation file, or choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project.	Patient_Tracker

**Comment by DoDoENT** [comment]
Hi sirius,

does the demo app work for you? Which architecture have you chosen in Visual Studio? You must select "ARM", not "Any CPU".

**Comment by sirius2013** [comment]
I already try to select ARM, x86, x64, Any CPU, but no lucky,

could you let me know where is demo app?

could you post link for demo app?

Thank you

**Comment by DoDoENT** [comment]
You can run [initDemoApp.sh](https://github.com/PDF417/pdf417-phonegap/blob/master/initDemoApp.sh) script that will generate demo app for both Android, iOS and WP8. The script requires BASH environment.

**Comment by sirius2013** [comment]
okay, I will try and will let you know, Thank you.

**Comment by sirius2013** [comment]
One quick question, this plugin is not working Simulator?
(I know Scan function will not work, but app itself could run)

**Comment by sirius2013** [comment]
Like Barcode scan plugin.

**Comment by sirius2013** [comment]
![image](https://cloud.githubusercontent.com/assets/5020713/10726571/72e72122-7c0e-11e5-8cd9-020b8d972f01.png)

**Comment by sirius2013** [comment]
AND I got same error with Demo app after copy Microblink.dll file from plugin folder.

**Comment by sirius2013** [comment]
Important Note: I got same error after copy Microblink.dll file from plugin folder.

**Comment by sirius2013** [comment]
![image](https://cloud.githubusercontent.com/assets/5020713/10726660/0af2a34c-7c0f-11e5-9bb2-5fadd6576ca8.png)

**Comment by DoDoENT** [comment]
In your screenshot, you have selected "x86" architecture. Please select "ARM". Both Microblink.dll and PDF417.dll are compiled only for "ARM" platform. You also must also select "Device", not "Emulator" (when compiling for Emulator, x86 assembly is generated even if you select "ARM" architecture).

**Comment by sirius2013** [comment]
okay, I will try that.
so I have other question for usage.
![image](https://cloud.githubusercontent.com/assets/5020713/10729195/c79235f4-7c22-11e5-9f6d-1cd506bfaced.png)

types, options, licenseiOs, licenseAndroid

We need to add licenseWindows?

**Comment by DoDoENT** [comment]
Yes,
[demo app](https://github.com/PDF417/pdf417-phonegap/blob/master/index.js#L149) is updated but documentation is not.

**Comment by sirius2013** [comment]
Okay. Thank you
Unfortunately I got this issue again.
Any suggestion for this?
Thank you
![image](https://cloud.githubusercontent.com/assets/5020713/10730390/a6a4bb2a-7c2a-11e5-8b1f-ef702b3bd693.png)

**Comment by DoDoENT** [comment]
Hi,can you provide logs?

**Comment by sirius2013** [comment]
how to get logs? I built app and got xap file and copy to SD card and open XAP file on file explorer.
and Tap to install.
And then it says like this.

I got some solution from stackoverflow. but I am not sure we must publish app on the store first.
Look at link
http://stackoverflow.com/questions/25364419/cant-install-company-app-on-windows-phone-8

Thank you

**Comment by DoDoENT** [comment]
I thought you get this error when launching the app. On Windows, you *must* install your app from Visual Studio by clicking Run icon. If you attempt installing app by building it, copying to device and then opening the file on device, installation will fail. This is Microsoft's policy to prevent distribution of apps via channels other than Windows Store (Apple has similar policy).

**Comment by sirius2013** [comment]
So to install from device, we need to publish app on the store first?

**Comment by sirius2013** [comment]
In general, developers has visual studio, so can install easily, but clients don't have and don't need that. only xap file for installation,

What is the best way?

**Comment by DoDoENT** [comment]
For development, you need to install via Visual Studio. Once your app is ready, you will publish it to Windows Store. From Windows Store normal users can install app without Visual Studio. If you simply need a beta test, then read [this article](https://msdn.microsoft.com/en-us/library/windows/apps/mt185377.aspx) (basically, your app needs to be published to Windows Store, but with specific settings described on given page).

**Comment by sirius2013** [comment]
Okay, I got it. Thank you

**Comment by sirius2013** [comment]
and then do you have any submitted wp app with pdf417 plugin feature?

**Comment by sirius2013** [comment]
I need to show working pdf417 wp plugin version without visual studio.
Thank you

**Comment by sirius2013** [comment]
so we will  buy licenses and will use this wp plugin for several apps.

**Comment by DoDoENT** [comment]
Hi sirius,

we do not have PDF417.mobi demo app available on Windows Store.

**Comment by sirius2013** [comment]
Hi.
Okay then could you provide demo video to show working version on wp8 platform?

so we can get approve.

Thank you

**Comment by Cerovec** [comment]
We have a generic video for all platforms: https://vimeo.com/109403864

Also, we're working on adding a demo app to marketplace.

Please close this issue if the original problem was solved.

**Comment by sirius2013** [comment]
well, okay, I will close this issue.
but I think vimeo video shows iPhone version instead  of windows phone version.

Great! I really need that, so Please let me know once that is done!
