### ISSUE TITLE
Android Eclipse version.

### ISSUE THREAD

**Issue by sirius2013** [PDF417/pdf417-phonegap#20]
Hello.
I tried to build app on eclipse.
but failed. main java file has tons of errors. 
I don't think lib file is imported correctly.

could you write document for Eclipse?

![image](https://cloud.githubusercontent.com/assets/5020713/11586355/7288371c-9aad-11e5-9218-ac7d4899c107.png)

**Comment by DoDoENT** [comment]
Hi, eclipse is deprecated IDE and we do not provide demo apps for it anymore. If you are interested in step-by-step integration for Eclipse, you can check our [documentation](https://github.com/PDF417/pdf417-android#eclipseIntegration).

**Comment by sirius2013** [comment]
Thank you so much for your fast reply, okay, I will check now.
Thanks again

**Comment by DoDoENT** [comment]
Hi @sirius2013,

is this issue resolved for you? Can we close it?

**Comment by sirius2013** [comment]
ok
