### ISSUE TITLE
pdf417-phonegap not working when started from inappbrowser-like cordova plugins

### ISSUE THREAD

**Issue by maurodsantos** [PDF417/pdf417-phonegap#21]
Hi guys,
I'm trying to use your plugin in a web-app which is loaded in a cordova app using the 
inappbrowser or themeablebrowser plugins. when I started the pdf417 view by pushing a button from the inappbrowser context I have the following mistake:
Warning: Attempt to present <CameraViewController: 0x13f309220> on <MainViewController: 0x13dd26620> whose view is not in the window hierarchy!

And I cannot see the camera.
I've tried a fix, to get the cameraviewcontroller to the parent view (on the native code), which shows the camera, but them when I get a results from your plugin, and get back to the inappbrowser view it comes blank.

this happens for the iPad mini 2 in the IOS 9.0.

Did you have an issue related with this one?
Thank you for your time,

Mauro

**Comment by Cerovec** [comment]
Hi Mauro,

to understand the first error, you have to know that pdf417 library
presents camera view controller using method presentViewController, on top
of currently presented view controller. The exact line of code which does
that is here
<https://github.com/PDF417/pdf417-phonegap/blob/master/Pdf417/src/ios/sources/CDVpdf417.m#L244>
.

Here pdf417 uses viewController property of the CDVPlugin class. Apparently
in your app this returns a viewController whose view is not in the view
hierarchy (this can happen, for example, if the view controller is
currently being dismissed).

pdf417 SDK cannot do much about that. You can either modify your app so
that this property returns a valid view controller, your you can change the
plugin so that it work for your use case.

The second error I didn't really understand. Which view controller comes
blank, camera, or inappbrowser?

Is it possible you share javascript code u use for invoking the scanner?

Thanks,
Jurica.



On Thu, Jan 7, 2016 at 12:33 PM, Mauro <notifications@github.com> wrote:

> Hi guys,
> I'm trying to use your plugin in a web-app which is loaded in a cordova
> app using the
> inappbrowser or themeablebrowser plugins when I started the pdf417 view by
> pushing a button from the inappbrowser context I have the following mistake:
> Warning: Attempt to present on whose view is not in the window hierarchy!
>
> And I cannot see the camera
> I've tried a fix, to get the cameraviewcontroller to the parent view (on
> the native code), which shows the camera, but them when I get a results
> from your plugin, and get back to the inappbrowser view it comes blank
>
> this happens for the iPad mini 2 in the IOS 90
>
> Did you have an issue related with this one?
> Thank you for your time,
>
> Mauro
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDF417/pdf417-phonegap/issues/21>.
>



-- 
Jurica Cerovec, M.Sc.

mobile: +385 98 993 8076
skype: cerovec

http://photomath.net
http://microblink.com

**Comment by maurodsantos** [comment]
Thanks for your help. I did change that line to


[self.getTopPresentedViewController
presentViewController:scanningViewController
animated:YES completion:nil];

and then I was able to see the camera, when issued from the inappbrowser
plugin,
but on completion of the camera task, I no longer see the inappbrower
screen with my webpage.

I wonder if that is because the completion:nil (in that same line of code),
and on completion I should present the inappbrowser view, which I need to
identify correctly.

the code I'm using is:
(the pdf417 function)

function runBarcode(event, ref) {


     * Scan these barcode types

     * Available: "PDF417", "USDL", "QR Code", "Code 128", "Code 39", "EAN
13", "EAN 8", "ITF", "UPCA", "UPCE", "Aztec", "Data Matrix"

     */

    var types = ["PDF417", "Code 128"];



    /**

     * Initiate scan with options

     * NOTE: Some features are unavailable without a license

     * Obtain your key at http://pdf417.mobi

     */



    var options = {

        beep: true, // Beep on

        noDialog: true, // Skip confirm dialog after scan

        uncertain: false, //Recommended

        quietZone: false, //Recommended

        highRes: false, //Recommended

        inverseScanning: false,

        frontFace: false

    };


    // Note that each platform requires its own license key


    // This license key allows setting overlay views for this application
ID: mobi.pdf417.demo

    var licenseiOs =
"XE3DN5MH-6BYS3TA7-HAUQHBDD-NRKVH4DV-WPDPF4NF-6PAUBFXW-IYVZBUX7-CXNQ4P7Z";



    // This license is only valid for package name "mobi.pdf417.demo"

    var licenseAndroid =
"UDPICR2T-RA2LGTSD-YTEONPSJ-LE4WWOWC-5ICAIBAE-AQCAIBAE-AQCAIBAE-AQCFKMFM";


    // This license is only valid for Product ID
"e2994220-6b3d-11e5-a1d6-4be717ee9e23"

    var licenseWP8 =
"5JKGDHZK-5WN4KMQO-6TZU3KDQ-I4YN67V5-XSN4FFS3-OZFAXHK7-EMETU6XD-EY74TM4T";

    cordova.plugins.pdf417Scanner.scan(

            // Register the callback handler

                    function callback(scanningResult) {

                        // handle cancelled scanning

                        if (scanningResult.cancelled == true) {

                          //ref = window.open(e.url, '_blank');

                          ref.executeScript({code: "alert('Barcode-scanner
canceled');"});

alert('Barcode-scanner canceled');

                          return -1;

                        }


                        // Obtain list of recognizer results

                        var resultList = scanningResult.resultList;

                        var data = [];

                        // Iterate through all results

                        for (var i = 0; i < resultList.length; i++) {


                            // Get individual resilt

                            var recognizerResult = resultList[i];


                            if (recognizerResult.resultType == "Barcode
result") {

                                // handle Barcode scanning result


                                var raw = "";

                                if (typeof (recognizerResult.raw) !=
"undefined" && recognizerResult.raw != null) {

                                    raw = hex2a(recognizerResult.raw);

                                }


                                data.push({raw: raw, data:
recognizerResult.data, type: recognizerResult.type});


                            }

                        }

                        if (data.length > 0) {

                            ref.executeScript({code: "alert('" + data[0].data
+ "');"}, null);

                        } else {

                            ref.executeScript({code: "alert('No barcode
found');"}, null);

                        }

                    },

                    // Register the error callback

                            function errorHandler(err) {

                                alert('Error: ' + err);

                                console.log("SEND:running camera");

                                return -2;

                            },

                            types, options, licenseiOs, licenseAndroid,
licenseWP8

                            );


                }

them to run the function from the themeablebrowser(extension from the
inappbrowser):

        var app = {

            // Application Constructor

            initialize: function () {

                this.bindEvents();

            }

            ,


            bindEvents: function () {

                document.addEventListener('deviceready', this.onDeviceReady,
false);

            },


            onDeviceReady: function () {


                var ref = cordova.ThemeableBrowser.open('
http://vps183888.ovh.net', '_blank', {

                                              statusbar: {

                                              color: '#ffffffff'

                                              },

                                              toolbar: {

                                              height: 44,

                                              color: '#f0f0f0ff'

                                              },

                                              title: {

                                              color: '#003264ff',

                                              showPageTitle: true

                                              },

                                              customButtons: [

                                                              {

                                                              wwwImage:
'img/ic_camera.png',


wwwImagePressed: 'img/ic_camera.png',


wwwImageDensity: 2,

                                                              align: 'right'
,

                                                              event:
'sharePressed'

                                                              }

                                                              ],



                                              backButtonCanClose: true

                                              }).addEventListener(
'sharePressed', function(e) {




runBarcode(e,ref);


                              //alert(e.url);






}).addEventListener(cordova.ThemeableBrowser.EVT_ERR, function(e) {


                                                  console.error(e.message);



}).addEventListener(cordova.ThemeableBrowser.EVT_WRN, function(e) {



console.log(e.message);


                                                                      });



            },

            // Update DOM on a Received Event

            receivedEvent: function (id) {

                console.log('Received Event: ' + id);

            }


        };


        app.initialize();


Thank you for your time,
Mauro




On Thu, Jan 7, 2016 at 12:04 PM, Jurica Cerovec <notifications@github.com>
wrote:

> Hi Mauro,
>
> to understand the first error, you have to know that pdf417 library
> presents camera view controller using method presentViewController, on top
> of currently presented view controller. The exact line of code which does
> that is here
> <
> https://github.com/PDF417/pdf417-phonegap/blob/master/Pdf417/src/ios/sources/CDVpdf417.m#L244
> >
> .
>
> Here pdf417 uses viewController property of the CDVPlugin class. Apparently
> in your app this returns a viewController whose view is not in the view
> hierarchy (this can happen, for example, if the view controller is
> currently being dismissed).
>
> pdf417 SDK cannot do much about that. You can either modify your app so
> that this property returns a valid view controller, your you can change the
> plugin so that it work for your use case.
>
> The second error I didn't really understand. Which view controller comes
> blank, camera, or inappbrowser?
>
> Is it possible you share javascript code u use for invoking the scanner?
>
> Thanks,
> Jurica.
>
>
>
> On Thu, Jan 7, 2016 at 12:33 PM, Mauro <notifications@github.com> wrote:
>
> > Hi guys,
> > I'm trying to use your plugin in a web-app which is loaded in a cordova
> > app using the
> > inappbrowser or themeablebrowser plugins when I started the pdf417 view
> by
> > pushing a button from the inappbrowser context I have the following
> mistake:
> > Warning: Attempt to present on whose view is not in the window hierarchy!
> >
> > And I cannot see the camera
> > I've tried a fix, to get the cameraviewcontroller to the parent view (on
> > the native code), which shows the camera, but them when I get a results
> > from your plugin, and get back to the inappbrowser view it comes blank
> >
> > this happens for the iPad mini 2 in the IOS 90
> >
> > Did you have an issue related with this one?
> > Thank you for your time,
> >
> > Mauro
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PDF417/pdf417-phonegap/issues/21>.
> >
>
>
>
> --
> Jurica Cerovec, M.Sc.
>
> mobile: +385 98 993 8076
> skype: cerovec
>
> http://photomath.net
> http://microblink.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDF417/pdf417-phonegap/issues/21#issuecomment-169643393>
> .
>



-- 
Mauro D. Santos
DPhil Student,
CDT in Healthcare Innovation,
Institute of Biomedical Engineering, University of Oxford

**Comment by maurodsantos** [comment]
just to complete:
[self.getTopPresentedViewController presentViewController
:scanningViewController animated:YEScompletion:nil];

-(UIViewController *)getTopPresentedViewController {

    UIViewController *presentingViewController = self.viewController;

    while(presentingViewController.presentedViewController != nil)

    {

        presentingViewController = presentingViewController.
presentedViewController;

    }

    return presentingViewController;

}

On Thu, Jan 7, 2016 at 12:04 PM, Jurica Cerovec <notifications@github.com>
wrote:

> Hi Mauro,
>
> to understand the first error, you have to know that pdf417 library
> presents camera view controller using method presentViewController, on top
> of currently presented view controller. The exact line of code which does
> that is here
> <
> https://github.com/PDF417/pdf417-phonegap/blob/master/Pdf417/src/ios/sources/CDVpdf417.m#L244
> >
> .
>
> Here pdf417 uses viewController property of the CDVPlugin class. Apparently
> in your app this returns a viewController whose view is not in the view
> hierarchy (this can happen, for example, if the view controller is
> currently being dismissed).
>
> pdf417 SDK cannot do much about that. You can either modify your app so
> that this property returns a valid view controller, your you can change the
> plugin so that it work for your use case.
>
> The second error I didn't really understand. Which view controller comes
> blank, camera, or inappbrowser?
>
> Is it possible you share javascript code u use for invoking the scanner?
>
> Thanks,
> Jurica.
>
>
>
> On Thu, Jan 7, 2016 at 12:33 PM, Mauro <notifications@github.com> wrote:
>
> > Hi guys,
> > I'm trying to use your plugin in a web-app which is loaded in a cordova
> > app using the
> > inappbrowser or themeablebrowser plugins when I started the pdf417 view
> by
> > pushing a button from the inappbrowser context I have the following
> mistake:
> > Warning: Attempt to present on whose view is not in the window hierarchy!
> >
> > And I cannot see the camera
> > I've tried a fix, to get the cameraviewcontroller to the parent view (on
> > the native code), which shows the camera, but them when I get a results
> > from your plugin, and get back to the inappbrowser view it comes blank
> >
> > this happens for the iPad mini 2 in the IOS 90
> >
> > Did you have an issue related with this one?
> > Thank you for your time,
> >
> > Mauro
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/PDF417/pdf417-phonegap/issues/21>.
> >
>
>
>
> --
> Jurica Cerovec, M.Sc.
>
> mobile: +385 98 993 8076
> skype: cerovec
>
> http://photomath.net
> http://microblink.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDF417/pdf417-phonegap/issues/21#issuecomment-169643393>
> .
>



-- 
Mauro D. Santos
DPhil Student,
CDT in Healthcare Innovation,
Institute of Biomedical Engineering, University of Oxford

**Comment by maurodsantos** [comment]
I made it work by using an iframe directly.
Best,
Mauro
