### ISSUE TITLE
CLI adding android

### ISSUE THREAD

**Issue by firescout** [PDF417/pdf417-phonegap#24]
When i run 
`ionic plugin add /Downloads/pdf417-phonegap-master/Pdf417`
It throws a error 
`Error: Uh oh!
"/plugins/mobi.pdf417.Pdf417Scanner/src/android/pdf417-android/Pdf417MobiDemo/pdf417MobiDemo/src/main/res/raw/beep.mp3" not found!`

The downloaded folder doesn't have a beep.mp3 

Anyone have some on this?

**Comment by DoDoENT** [comment]
Have you [initialised submodules](https://github.com/PDF417/pdf417-phonegap#submodules) after cloning?

**Comment by firescout** [comment]
i did not clone. downloaded as zip.
when i run 
`git clone git@github.com:PDF417/pdf417-phonegap.git`
It shows the following
`Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.`

**Comment by DoDoENT** [comment]
This error indicates that you have set wrong SSH key for your GitHub account. More info here: https://help.github.com/articles/error-permission-denied-publickey/

**Comment by firescout** [comment]
ok ive cloned it now thanks.
when i run submodule commands i get the following

**INIT**
`git submodule init`
zSubmodule 'Pdf417/src/android/pdf417-android' (https://github.com/PDF417/pdf417-android.git) registered for path 'Pdf417/src/android/pdf417-android'`

**UPDATE** 
`Cloning into 'Pdf417/src/android/pdf417-android'...`
`remote: Counting objects: 6998, done.`
`remote: Compressing objects: 100% (28/28), done.`
`error: RPC failed; result=56, HTTP code = 200B | 257.00 KiB/s`
`fatal: The remote end hung up unexpectedly`
`fatal: early EOF`
`fatal: index-pack failed`
`Clone of 'https://github.com/PDF417/pdf417-android.git' into submodule path 'Pdf417/src/android/pdf417-android' failed`

**Comment by DoDoENT** [comment]
> fatal: The remote end hung up unexpectedly

This indicates a connection glitch between you and GitHub. I've just tried cloning both `phonegap` repo and its submodules and everything worked correctly.

**Comment by firescout** [comment]
thank you DoDoENT
for the assistance
