### ISSUE TITLE
I Can't scan serveral times

### ISSUE THREAD

**Issue by sirius2013** [PDF417/pdf417-phonegap#25]
Yes. Scan works, but it works only one time, If I tried to scan again, then scan is not working. 
here is console log.
hope this is helpful.

Patient Tracker[287:60680] Warning: Attempt to present on whose view is not in the window hierarchy!
Patient Tracker[287:60680] Warning: Attempt to present on whose view is not in the window hierarchy!
Patient Tracker[287:60680] Warning: Attempt to present on whose view is not in the window hierarchy!
Patient Tracker[287:60680] Error in Success callbackId: Pdf417Scanner326430938 : ReferenceError: Can't find variable: hex2a
Patient Tracker[287:60680] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates.

**Comment by Pickles112358** [comment]
Hello,

Have you tried using our PhoneGap demo app? You can create it by running the script initDemoApp.sh.
When the script is run, xcode project file should be created at "Pdf417Demo/platforms/ios".
Could you run the app and check if the same error appears?

**Comment by sirius2013** [comment]
It seems it working
but I have barcode scan and camera features,  pls see my log.
If I remove pdf417 plugin, everything is okay,
but when I add this plugin, I can scan only one time, and try to scan DL or Barcode Scan or Take photo is not working.

**Comment by Pickles112358** [comment]
Could you have an issue similar to this one:
https://github.com/PDF417/pdf417-phonegap/issues/21
?

**Comment by sirius2013** [comment]
Hi
Thank you for link.
It seems similar, but I don't have any inappbrowser.

I have three buttons on the app.
DL scan, Barcode Scan, Take a photo.
DL Scan works fine one time, I got result, and click buttons again to scan or take photo.

but nothing is happened.
This is issue I got. :)
Thanks

**Comment by Pickles112358** [comment]
The problem is that our scanningViewController is trying to be presented on top of a ViewController which is not in the window hierarchy. This could be a problem with your code handling the first scanning results. You could try the solution posted in the linked issue as problem is the same and it is not related to inappbrowser.

Alternatively, you could try replacing these 2 lines in our plugin:
https://github.com/PDF417/pdf417-phonegap/blob/master/Pdf417/src/ios/sources/CDVpdf417.m#L358
and
https://github.com/PDF417/pdf417-phonegap/blob/master/Pdf417/src/ios/sources/CDVpdf417.m#L361
This could fix the issue but we can't be certain as this issue isn't related to our SDK.

**Comment by sirius2013** [comment]
okay, but what means replace?
what is trying code for replacement for above two lines?
Thanks

**Comment by Pickles112358** [comment]
Sorry,

Switch the position of them :) (keep them both in code)

**Comment by sirius2013** [comment]
No lucky.

Scan first works fine. and second time not working.

But close app (Tap Home icon on iphone) and run app again, then DL Scanner appeared.

Patient Tracker[499:190754] Error in Success callbackId: Pdf417Scanner1142733526 : ReferenceError: Can't find variable: hex2a
Patient Tracker[499:190754] Phone default language unsupported, setting English
Patient Tracker[499:190754] THREAD WARNING: ['Pdf417Scanner'] took '75.639893' ms. Plugin should use a background thread.
Patient Tracker[499:190754] Phone default language unsupported, setting English
Patient Tracker[499:190754] THREAD WARNING: ['Pdf417Scanner'] took '206.644043' ms. Plugin should use a background thread.
Patient Tracker[499:190754] Warning: Attempt to present <CameraViewController: 0x1301954f0> on <MainViewController: 0x12ee3be20> whose view is not in the window hierarchy!
Patient Tracker[499:190754] Warning: Attempt to present <CDVCameraPicker: 0x12f884200> on <MainViewController: 0x12ee3be20> whose view is not in the window hierarchy!

**Comment by sirius2013** [comment]
And old version of this plugin worked fine in my project.

**Comment by sirius2013** [comment]
Hi.
Any good news for this?
Thank s

**Comment by Cerovec** [comment]
Hi,
did you manage to resolve this issue?
