### ISSUE TITLE
iOS SDK 4.2.2

### ISSUE THREAD

**Issue by mkuklis** [PDF417/pdf417-phonegap#27]
Hey guys I was wondering if it would be possible for you to update the iOS SDK to 4.2.2 ?https://github.com/PDF417/pdf417-ios/releases/tag/v4.2.2

**Comment by Cerovec** [comment]
Hi @mkuklis,
We're closing this issue as solved (the latest release uses iOS SDK 5.1.1).
Let us know if we can help in any other way.
Best,
Jurica.
