### ISSUE TITLE
update README.md documentation for submodules?

### ISSUE THREAD

**Issue by mpayne-sds** [PDF417/pdf417-phonegap#30]
I was unable to successfully install the plugin based on the README directions... 
Ended up with this error:
Installing "mobi.pdf417.Pdf417Scanner" for android
Failed to install 'mobi.pdf417.Pdf417Scanner':CordovaError: Uh oh!
"../plugins/mobi.pdf417.Pdf417Scanner/src/android/pdf417-android/Pdf417MobiDemo/pdf417MobiDemo/src/main/res/raw/beep.mp3" not found!

Running the following command seemed to help.

git submodule update --init --recursive

**Comment by Cerovec** [comment]
Hi @mpayne-sds,

we're closing this issue since we updated the readme.

Please let us know if you need any other help with the SDK in the meantime.

Best,
Jurica.
