### ISSUE TITLE
Add description for addEmbedded.js iOS script.

### ISSUE THREAD

**Issue by rnagella** [PDF417/pdf417-phonegap#45]
Hello Team,

Would you kindly add a detailed description on what `addEmbedded.js` script does for iOS. It may or not work what it is supposed to do and when we are in that situation, it helps to figure out the issue in one's situation.

https://github.com/PDF417/pdf417-phonegap/blob/master/Pdf417/scripts/addEmbedded.js

**Comment by jcular** [comment]
Hi @rnagella,

this script adds Microblink framework as embedded framework in the xcode project. See [this]( 
https://stackoverflow.com/questions/36650522/custom-cordova-plugin-add-framework-to-embedded-binaries) on stackoverflow. But it might no longer be necessary if cordova can handle that.

Kind regards,
Jure

**Comment by jcular** [comment]
Script removed in #48 because it's no longer needed.
