### ISSUE TITLE
Expecting char " in ios project name

### ISSUE THREAD

**Issue by rnagella** [PDF417/pdf417-phonegap#46]
`Problem`:
The ios script is expecting the project name to be wrapped in quotes.
https://github.com/PDF417/pdf417-phonegap/blob/master/Pdf417/scripts/addEmbedded.js#L91

Pleae check if the project name is wrapped in quotes, then only remove it. don't make it a default case.

**Comment by jcular** [comment]
Hi @rnagella,

as stated in #45 this script might no longer be necessary I'll test it and see if we can remove it.

Kind regards,
Jure

**Comment by jcular** [comment]
Script removed in #48 because it's no longer needed.
